### ISSUE TITLE
anviz_sync.anviz.DeviceException: Error in response

### ISSUE THREAD

**Issue by joseluisbossio** [coyotevz/anviz-sync#2]
Hi, after run the setup and configured the anviz-sync.ini, I ran the following command: python sync.py

But, unfortunately I recived the following error:

Traceback (most recent call last):
  File "sync.py", line 97, in <module>
    main()
  File "sync.py", line 93, in main
    sync(progress=progress, force_all=force_all)
  File "sync.py", line 53, in sync
    total = getattr(clock.get_record_info(),
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anviz_sync-0.1.0-py3.6.egg\anviz_sync\anviz.py", line 258, in get_record_info
    it = iter(self._get_response(CMD_GET_RECORD_INFO))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anviz_sync-0.1.0-py3.6.egg\anviz_sync\anviz.py", line 217, in _get_response
    raise DeviceException("Error in response")
anviz_sync.anviz.DeviceException: Error in response

**Comment by gedece** [comment]
having a similar issue with this. 

from anviz import Device
from configparser import ConfigParser

config = ConfigParser()
config.read('anviz-sync.ini')
dev_id = config.getint('anviz', 'device_id')
ip_addr = config.get('anviz', 'ip_addr')
ip_port = config.getint('anviz', 'ip_port')


reloj = Device(dev_id,ip_addr,ip_port)

reloj.check_connected()

datos = reloj.get_information()

print (datos)


Traceback (most recent call last):
  File "test.py", line 15, in <module>
    datos = reloj.get_information()
  File "C:\TEST\anviz\anviz-sync-master\anviz_sync\anviz.py", line 229, in get_information
    data = self._get_response(CMD_GET_INFO)
  File "C:\TEST\anviz\anviz-sync-master\anviz_sync\anviz.py", line 217, in _get_response
    raise DeviceException("Error in response")
anviz.DeviceException: Error in response
>Exit code: 1

**Comment by coyotevz** [comment]
Hello, which model of Anviz device are you using? which firmware version? I only tested this code with Anviz A300 firmware version: 01.53.A2
Newer firmware versions have changed communication protocol.

**Comment by victorv2k** [comment]
Hello, then with a firmware greater than 01.53.A2, does anviz sync not work? I have the model A300 and I get the same error.

**Comment by omicronvt** [comment]
Hello, in A300 firmware  01.74.A2 works. 
I have another A300 with firmware 02.31.A1 that gives me "checksum error" on download_records ... Any idea ? Thanks

**Comment by coyotevz** [comment]
Hello, the newer firmware versions have changed the communication protocol. I need the specifications for the version of the communication protocol newer than **01.74.A2**. Apparently this communication protocol is not public, if someone has it we can adapt this software to new firmware versions. Sorry
